name = "tele-bot-test"
main = "worker.js"
compatibility_date = "2024-11-21"

# এইখানে আপনার গোপন চাবিগুলো থাকবে
[vars]
BOT_TOKEN = "8205025354:AAHcabaH_MPU8RpOb8xicmL-12Ws0ujaMBo"
GEMINI_API_KEY = "AIzaSyDHQSN3UC-1gOsiNJf8Umc5pb-rW2BqCTU"

[[d1_databases]]
binding = "DB"
database_name = "tele-bot-db"
database_id = "5c69f0b8-7d44-4f1d-82d5-ba1461045bb5"
