name = "tele-bot-test"
main = "worker.js"
compatibility_date = "2024-11-24"

[vars]
# আপনার টেলিগ্রাম বটের টোকেন
BOT_TOKEN = "8205025354:AAHcabaH_MPU8RpOb8xicmL-12Ws0ujaMBo"

# আপনার ব্যাকএন্ড এপিআই লিংক (যেখানে প্রশ্ন পাঠানো হবে)
# লক্ষ্য করুন: কোডে /ask যোগ করা আছে, তাই এখানে শুধু মূল ডোমেইন দিন
API_BASE = "https://ff930dfe-3447-4745-9030-2102395ef11c-00-3sbm2vjl7iscd.sisko.replit.dev"
